#expose classes to predict for this language
# for each class expose the column in the truth.txt file
# and whether it is a classification or regression problem

userid:
    column: 0
    data_only: True
    result_column: 0
    result_label: id
media:
    data_only: True
    result_column: 1
    result_label: type
lang:
    data_only: True
    result_column: 2
    result_label: lang
gender:
    column: 1
    type: classification
    recipe: gender.yml
    result_column: 4
    result_label: gender
age:
    column: 2
    type: classification
    recipe: age.yml
    result_column: 3
    result_label: age_group
